### ISSUE TITLE
Pydantic validation error when using customfilewrite tool

### ISSUE THREAD

**Issue by evmond1** [strnad/CrewAI-Studio#29]
Btw, big kudos, been toying with doing this myself..  but its a big task and I'm not the best developer. Great platform

FYI, i ran into a number issues when using the customfilewrite tool, around pydantic validation errors. Spent a little time with chatgpt (A complete fraud I know) and after a few goes around the houses, the custom_tools code I now have works and the tool works. see below :

[custom_tools.txt](https://github.com/user-attachments/files/17181293/custom_tools.txt)

**Comment by strnad** [comment]
it should be fixed already. thanks a lot
