### ISSUE TITLE
ollama uasage 

### ISSUE THREAD

**Issue by omarkshoaib** [strnad/CrewAI-Studio#30]
what are all the configurations i need to do to use ollama?

**Comment by happyebb** [comment]
Same here on windows. I have installed the platform Ollama, as well as using "open webui" for the Ollama API service for end point. I have tried playing with the .evn config file and searched the web to no avail. Even toyed with the studio light model management option to use my local model. Perhaps its a simpler solution just starting us in the face. either way I was hoping there would be a predefined option or a comment in the .env file for local model use.

**Comment by arthughes1234** [comment]
Here as well. I am running CrewAI-Studio on a Windows 10 workstation successfully. My Agents can access OpenAI just fine. However, when I try to access our Ollama running on a Linux GPU server, I either get "ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable" or, if using the OpenAI interface method, "LiteLLM call failed: litellm.APIConnectionError: OllamaException - {"error":"model \"llama3.1\" not found, try pulling it first"}". Nothing seems to work. I can use Postman and post to the Ollama server and I get correct results. I'm sure I'm doing something wrong. We could really use the proper Ollama configuration, or suggestions on where to look! Thanks.

**Comment by strnad** [comment]
fixed :)

**Comment by arthughes1234** [comment]
Thanks for fixing it so quickly! Works like a charm and we are off running with scissors :)
