### ISSUE TITLE
Feature request: Variables for tasks

### ISSUE THREAD

**Issue by dakipro** [strnad/CrewAI-Studio#32]
Hey, love the project! 
I would like for all tasks to have similar context, say I am writing a youtube video on the topic "Dell vs Samsung Monitor" and I might have 5 different tasks one after the other (research, write draft, check facts, adjust writing style, suggest B-roll ideas etc). But next time I might compare "Samsung vs Apple phones", for the same crew, with same tasks.

it would be awesome if I could pass same option to all tasks, like
"The topic you are to do a research is { user_input } and you are to do your best work. If you do your best work, {motivational_string}"
or something like that

**Comment by strnad** [comment]
Hey, thanks for the feedback!

You can already do this! Just use curly brackets in the task definitions (e.g., {user_input} and {motivational_string}). You'll be prompted to fill them in before starting the crew, and the values will be shared across all tasks automatically.

Let me know if you have any questions!

**Comment by dakipro** [comment]
ha! that was fast, thanks man!
again, great job with making this, it has so many useful features, reminds me of Laravel for php (tool has focus on actually helping developers with things they do often).

I am just struggling to import more tools, even if I install them, python shows message that they are missing. But this is because I suck as python and do not understand different virtual environments etc.

It would be great if you could continue driving this tool in the future so it doesn't stale. I hope it will catch on :)
