### ISSUE TITLE
Error while running the Crew

### ISSUE THREAD

**Issue by EslamHosnyISO** [strnad/CrewAI-Studio#8]
Hello,
I'm facing the following error "Error: agent tools could not be created. 'NoneType' object has no attribute 'split'"

**Comment by strnad** [comment]
> Hello,
> I'm facing the following error "Error: agent tools could not be created. 'NoneType' object has no attribute 'split'"

which tools you use?

**Comment by Psychophoria** [comment]
Same problem here, seems related to the web/internet related tools... I didn't have this issue in previous builds, but the last few days I have been unable to resolve this.

**Comment by strnad** [comment]
@Psychophoria @EslamHosnyISO Thanks for reporting this issue. It should be fixed now. Please let me know if you encounter any other problems. 😊

**Comment by Psychophoria** [comment]
> @Psychophoria @EslamHosnyISO Thanks for reporting this issue. It should be fixed now. Please let me know if you encounter any other problems. 😊

Can't resist saying how much I appreciate all the time & energy you've put into this project - I have been lurking & testing for quite some time now, and the progress you have made is absolutely stunning. 

This is what I have ALWAYS longed for since the inception of CrewAI, and while many have attempted to make a GUI/UI interface, I could almost mistake this one for being native. 

I know myself and many other users are beyond pleased with your work, so please keep it up! Thank you so much!

**Comment by sam43b** [comment]
Hi Sir , 

thank you for sharing this awsome ui , i have this error in the first run :

2024-10-24 12:12:22,102 - 15592 - user_agent.py-user_agent:11 - WARNING: USER_AGENT environment variable not set, consider setting it to identify your requests.
2024-10-24 12:12:25.854 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Sam\Desktop\MyCrew\vnv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\Sam\Desktop\MyCrew\vnv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\app.py", line 4, in <module>
    from pg_agents import PageAgents
  File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\pg_agents.py", line 3, in <module>
    from my_agent import MyAgent
  File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\my_agent.py", line 6, in <module>
    from llms import llm_providers_and_models, create_llm
  File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\llms.py", line 68, in <module>
    "models": os.getenv("OLLAMA_MODELS").split(','),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

Best,

**Comment by strnad** [comment]
> Hi Sir ,
> 
> thank you for sharing this awsome ui , i have this error in the first run :
> 
> 2024-10-24 12:12:22,102 - 15592 - user_agent.py-user_agent:11 - WARNING: USER_AGENT environment variable not set, consider setting it to identify your requests. 2024-10-24 12:12:25.854 Uncaught app exception Traceback (most recent call last): File "C:\Users\Sam\Desktop\MyCrew\vnv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling result = func() ^^^^^^ File "C:\Users\Sam\Desktop\MyCrew\vnv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec exec(code, module.**dict**) File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\app.py", line 4, in from pg_agents import PageAgents File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\pg_agents.py", line 3, in from my_agent import MyAgent File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\my_agent.py", line 6, in from llms import llm_providers_and_models, create_llm File "C:\Users\Sam\Desktop\MyCrew\CrewAI-Studio\app\llms.py", line 68, in "models": os.getenv("OLLAMA_MODELS").split(','), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'split'
> 
> Best,

my bad, i forgot to handle the case when ollama parameters are not set in .env file. It should be fixed now. thank you for reporting it :)
